#version: '3.8'

services:
  vote:
    build: ./Vote
    ports:
      - "5000:80"
    environment:
      - OPTION_A=Cats
      - OPTION_B=Dogs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    volumes:
      - ./Vote:/app

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_DB: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  result:
    build: ./Result
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

